### ISSUE TITLE
Fails to create index for UTF strings

### ISSUE THREAD

**Issue by sadikovi** [lightcopy/parquet-index#25]
Fails to create due to #9. Exception stack trace:
```
java.lang.IllegalArgumentException: requirement failed: Min é is greater than max a
	at scala.Predef$.require(Predef.scala:224)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetStringStatistics.<init>(statistics.scala:171)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetStatisticsRDD$.convertStatistics(ParquetStatisticsRDD.scala:238)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetStatisticsRDD$$anonfun$5.apply(ParquetStatisticsRDD.scala:219)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetStatisticsRDD$$anonfun$5.apply(ParquetStatisticsRDD.scala:212)
```

- Example to reproduce:
```scala
Seq("a", "é").toDF("name").coalesce(1).write.parquet("temp/bad.parquet")
spark.read.parquet("temp/bad.parquet").where("name > 'a'").show
```
When trying the same query with index, exception above is thrown.

- Example to show incorrect result:
```scala
Seq("aa", "bé", "bb").toDF("name").coalesce(1).write.parquet("temp/bad2.parquet")
```

```scala
spark.read.parquet("temp/bad2.parquet").where("name > 'bb'").show
```
returns this result:
```shell
+----+
|name|
+----+
|  bé|
+----+
```

```
spark.index.create.indexByAll.parquet("temp/bad2.parquet")
spark.index.parquet("temp/bad2.parquet").where("name > 'bb'").show
```
returns wrong result:
```shell
+----+
|name|
+----+
+----+
```

**Comment by sadikovi** [comment]
Fixed in #31.
