### ISSUE TITLE
Fails for empty blocks

### ISSUE THREAD

**Issue by sadikovi** [lightcopy/parquet-index#40]
Querying table fails if one of the Parquet files is empty, because of the condition on non-empty blocks.
```shell
17/01/08 17:41:43 INFO IndexSourceStrategy: Applying index filters: IsNotNull(col1),EqualTo(col1,2)
java.lang.IllegalArgumentException: requirement failed: Parquet file status has empty blocks, required at least one block metadata
  at scala.Predef$.require(Predef.scala:224)
  at org.apache.spark.sql.execution.datasources.parquet.ParquetIndexCatalog.resolveSupported(ParquetIndexCatalog.scala:131)
  at org.apache.spark.sql.execution.datasources.parquet.ParquetIndexCatalog$$anonfun$pruneIndexedPartitions$2$$anonfun$8.apply(ParquetIndexCatalog.scala:144)
  at org.apache.spark.sql.execution.datasources.parquet.ParquetIndexCatalog$$anonfun$pruneIndexedPartitions$2$$anonfun$8.apply(ParquetIndexCatalog.scala:143)
```

**Comment by sadikovi** [comment]
Fixed in #41.
