### ISSUE TITLE
NullPointerException when running on Yarn

### ISSUE THREAD

**Issue by lonehacker** [lightcopy/parquet-index#81]
When running in Yarn mode, I get a NPE, same code works in local mode
`
context.index.create.indexBy('driverId', 'timestamp').parquet('s3://archival-store/test/bench1day7/gps/packet_date=2018-03-25/')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anshuls/parquet-index/python/src/lightcopy/index.py", line 122, in parquet
    self._createIndex(path)
  File "/home/anshuls/parquet-index/python/src/lightcopy/index.py", line 103, in _createIndex
    jcreate.createIndex(path)
  File "/usr/local/spark/latest/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/usr/local/spark/latest/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/usr/local/spark/latest/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 319, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o62.createIndex.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 36 in stage 1.0 failed 4 times, most recent failure: Lost task 36.3 in stage 1.0 (TID 116, ip-172-18-54-234.us-west-2.compute.internal, executor 1): java.lang.NullPointerException
	at org.apache.hadoop.fs.FileSystem.getDefaultUri(FileSystem.java:232)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:223)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetStatisticsRDD.compute(ParquetStatisticsRDD.scala:122)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1499)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1487)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1486)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1486)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:814)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1714)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1669)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1658)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:630)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2022)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2043)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2062)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2087)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:936)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:935)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetMetastoreSupport.createIndex(ParquetMetastoreSupport.scala:140)
	at org.apache.spark.sql.execution.datasources.IndexedDataSource$$anonfun$createIndex$2.apply(IndexedDataSource.scala:108)
	at org.apache.spark.sql.execution.datasources.IndexedDataSource$$anonfun$createIndex$2.apply(IndexedDataSource.scala:107)
	at org.apache.spark.sql.execution.datasources.Metastore.create(Metastore.scala:162)
	at org.apache.spark.sql.execution.datasources.IndexedDataSource.createIndex(IndexedDataSource.scala:107)
	at org.apache.spark.sql.CreateIndexCommand.createIndex(DataFrameIndexManager.scala:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.apache.hadoop.fs.FileSystem.getDefaultUri(FileSystem.java:232)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:223)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetStatisticsRDD.compute(ParquetStatisticsRDD.scala:122)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
`
It looks like the hadoopConf is somehow Null, although I'm able to access it in my shell just fine

**Comment by sadikovi** [comment]
Hi @lonehacker. Thanks for reporting the problem.
I have not tried saving tables with s3 bucket - I guess, now we know what happens:)

I will have a look by the end of this week, see if I can reproduce the problem and/or fix it. 
If you want, feel free to submit a patch meanwhile, if you figure out how to solve it too!

**Comment by lonehacker** [comment]
I think this issue is related to yarn, not s3 buckets
A minimal reproduction can be done inside spark-shell in YARN mode -

import com.github.lightcopy.util.SerializableConfiguration

val confBroadcast = sc.broadcast(new SerializableConfiguration(spark.sessionState.newHadoopConf()))

sc.parallelize(1 to 10).map(x=> confBroadcast.value.value).collect()

This gives 
res7: Array[org.apache.hadoop.conf.Configuration] = Array(null, null, null, null, null, null, null, null, null, null)

Have you tried running in YARN mode?

**Comment by sadikovi** [comment]
Thank you very much for the reproducer script.
I have not tried it in YARN mode, unfortunately. I only use spark standalone cluster manager. 

I will see if I can do anything about it.

**Comment by lonehacker** [comment]
Turns out this was due to KryoSerialization, turning that off made everything work perfectly
I'm facing another problem now though, the number of spark tasks while reading from indexed dataframe is too high -
df = context.index.parquet('s3://archival-store/test/bench1day7/gps/packet_date=2018-03-25/')
df.count()
Run 40000 tasks
whereas
df2 = spark.read.parquet('s3://archival-store/test/bench1day7/gps/packet_date=2018-03-25/')
df2.count()
runs only about 2000 tasks
this is negating the perfomance benefit of using parquet-index
Any ideas?

**Comment by sadikovi** [comment]
Nice! Should we fix the serialization bug somehow in the code?

Sorry about all the problems you are having with the indexing.

I think these many tasks happen because we treat each file independently, where Spark actually batches them based on a cost of opening a file. It looks like index decided to scan all files because of the filter. Can you check your filter? It should log whether or not it is applying it in the first place and how many files it selected. 

Can you comment on how many files are overall in the directory? I will look at the code to see how Spark decides to batch files into partitions, and why this code is different. Would appreciate any help with this.

**Comment by lonehacker** [comment]
Filter pushdown is working fine, if I run -
df = context.index.parquet('s3://archival-store/test/bench1day7/gps/packet_date=2018-03-25/').filter("driverId = 'Y2E0ZTNjMTY5'")
it only runs like 500 tasks, whereas without the filter it's running 40000, this looks correct.
My concern is just about the fact that 40000 partitions are being created for this dataset in the first place. Because of that, even after filtering out the files, we still need to run 500 tasks compared to the 2000 we would need to run without using index. Thus performance benefit is not much.
The directory has about 1486 Objects, total size - 272.7 GB
As per my understanding, the code to batch files in partitions is present in FileSourceScanExec, see here - https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/DataSourceScanExec.scala#L399
and from here - https://github.com/lightcopy/parquet-index/blob/master/src/main/scala/org/apache/spark/sql/execution/datasources/IndexSourceStrategy.scala#L99
it looks like you're just calling FileSourceScanExec directly, so as per my understanding, there should not be a difference in how the splits are calculated.

**Comment by lonehacker** [comment]
The expectation from my side is also to filter files only, I've taken care to ensure that files don't have too much mixed up statistics.
In terms of actual time 2000 tasks (normal read) is faster than 500 tasks (with 4*10 cores about 2.1min compared to 3.4min), the reason is that in 2000 tasks, it reading only the metadata in most cases, whereas the 500 tasks is reading entire files.
The ratio of task reduction due to parquet-index is quite encouraging (40000 tasks -> 500 tasks), so I'm sure we can get better performance if the initial number of tasks is reduced, imagine 2000 tasks -> 25 tasks, which will be blazing fast

**Comment by sadikovi** [comment]
Nah, Spark would still need to scan at least 500 files out of 2000, generally more. 

How do you know that it could reduce to 25 tasks? Then parquet-index filtering is not working correctly - it should have selected those instead. Try enabling column filters and see if that helps...

Something is not right in assembling file source exec, need to debug it. I will try running it tomorrow on large data.

Thanks!

**Comment by lonehacker** [comment]
Hey so I did more experiments and it looks like counts are also not matching for spark.index.parquet compared to spark.read.parquet . Parquet index seems to inflate counts by as much as a factor of 20?
spark.index.parquet("s3://archival-store/test/bench1day7/gps/").filter("driverId = 'Y2E0ZTNjMTY5'").count()
res9: Long = 114                                                                

scala> spark.read.parquet("s3://archival-store/test/bench1day7/gps/").filter("driverId = 'Y2E0ZTNjMTY5'").count()
res10: Long = 8  

Have you tried running with multiple parquet files?

**Comment by sadikovi** [comment]
Yes, of course. I tried building index with multiple Parquet files, since there is no point in running with one file.

Below are numbers that I ran this morning on partitioned table with more than 6 billion records and more than 20 columns (flat schema).

My tests are only with Spark standalone cluster manager and HDFS. I have not tested with S3 or YARN.
Couns match and number of tasks is reduced in some cases (depending on filter).
Spark also launches the same number of tasks (2349) when filter is trivial, e.g. we read all data.

```
scala> spark.read.parquet("/events/proxy_logs").filter("ip_address = 'XXX.XXX.XX.XXX'").count
res3: Long = 493451  
2349 tasks

scala> spark.index.parquet("/events/proxy_logs").filter("ip_address = 'XXX.XXX.XX.XXX'").count
res4: Long = 493451   
564 tasks

Time performance is more than 2x.

scala> spark.read.parquet("/events/proxy_logs").filter("domain = 'cdn.krxd.net'").count
res10: Long = 8306749
2330 tasks

scala> spark.index.parquet("/events/proxy_logs").filter("domain = 'cdn.krxd.net'").count
res9: Long = 8306749                                                            
2217 tasks

Time almost the same.

scala> spark.read.parquet("/events/proxy_logs").filter($"timestamp" === java.sql.Timestamp.valueOf("2015-08-20 03:01:36")).count
res12: Long = 7893     
2330 tasks

scala> spark.index.parquet("/events/proxy_logs").filter($"timestamp" === java.sql.Timestamp.valueOf("2015-08-20 03:01:36")).count
res11: Long = 7893
64 tasks

Time performance is 13x.
```

I am not sure how to fix your issues - I don't have a YARN setup handy to test. Would appreciate if you could follow through and submit a patch if necessary!

**Comment by lonehacker** [comment]
Hey, so I looked more into this and it looks like the problem is somewhere in partition Pruning code:
https://github.com/lightcopy/parquet-index/blob/7ef254eeb3c747898d491b0ac4596d98db68dac0/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetIndex.scala#L67
I guess this code is comparing the values of the partition but not on the correct partition, which leads to duplicate paths. Specifically the condition here https://github.com/lightcopy/parquet-index/blob/7ef254eeb3c747898d491b0ac4596d98db68dac0/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetIndex.scala#L75 
is matching multiple partitions in allPartitions with each selectedPartition. I guess the reason for this is that I have multiple partition columns and the values are different for only 1 for those columns, I guess the values variable associated with partition doesn't contain all the partition column values.
Anyway, on removing that piece of code, it works beatifully

**Comment by sadikovi** [comment]
@lonehacker thanks for debugging! Could you send or sketch your directory structure including partition directories (not the data files) in the comment? I would like to understand what directory structure causes it to fail, and reproduce it locally.
