### ISSUE TITLE
Failed to merge incompatible data types LongType and StringType

### ISSUE THREAD

**Issue by darouwan** [lightcopy/parquet-index#83]
It throws "SparkException: Failed to merge incompatible data types LongType  and StringType" while I create the index.

How does it come? And how to solve it?

**Comment by sadikovi** [comment]
Can you post the exception stacktrace? Thanks.

**Comment by darouwan** [comment]
Something like 
```
Caused by: org.apache.spark.SparkException: Failed to merge incompatible data types LongType and StringType
    at org.apache.spark.sql.types.StructType$.merge(StructType.scala:462)
    at org.apache.spark.sql.types.StructType$$anonfun$merge$1$$anonfun$apply$3.apply(StructType.scala:420)
    at org.apache.spark.sql.types.StructType$$anonfun$merge$1$$anonfun$apply$3.apply(StructType.scala:418)
    at scala.Option.map(Option.scala:145)
    at org.apache.spark.sql.types.StructType$$anonfun$merge$1.apply(StructType.scala:418)
    at org.apache.spark.sql.types.StructType$$anonfun$merge$1.apply(StructType.scala:415)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
    at org.apache.spark.sql.types.StructType$.merge(StructType.scala:415)
    at org.apache.spark.sql.types.StructType.merge(StructType.scala:333)
    at org.apache.spark.sql.execution.datasources.parquet.ParquetRelation$$anonfun$24$$anonfun$apply$9.apply(ParquetRelation.scala:829)
```

**Comment by sadikovi** [comment]
Thanks! I will have a look shortly.

**Comment by sadikovi** [comment]
Could you give a little bit more information around the issue? For example, some short code to reproduce. This error originates in Spark code, I assume after you have built the index. Without some necessary pre-steps I cannot debug the issue.
