### ISSUE TITLE
Using s3a for index metastore throws a "Wrong FS" exception

### ISSUE THREAD

**Issue by arunbhat** [lightcopy/parquet-index#86]
Thanks for creating this project to index parquet tables.  I tried to create the index metastore in s3 with the following default
spark.sql.index.metastore=s3a://xx/yy/index_metastore". I got an exception that said 

java.lang.IllegalArgumentException: Wrong FS: s3a://xxx/index_metastore/catalog/parquet/s3a/yyy/part-f-00002, expected: file:///
	at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:649)
	at org.apache.hadoop.fs.RawLocalFileSystem.pathToFile(RawLocalFileSystem.java:82)
	at org.apache.hadoop.fs.RawLocalFileSystem.mkdirsWithOptionalPermission(RawLocalFileSystem.java:518)
	at org.apache.hadoop.fs.RawLocalFileSystem.mkdirs(RawLocalFileSystem.java:504)
	at org.apache.hadoop.fs.ChecksumFileSystem.mkdirs(ChecksumFileSystem.java:694)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetStatisticsRDD$$anonfun$1.apply(ParquetStatisticsRDD.scala:141)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetStatisticsRDD$$anonfun$1.apply(ParquetStatisticsRDD.scala:138)

I updated 
https://github.com/lightcopy/parquet-index/blob/master/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetStatisticsRDD.scala#L122 to:
  val filterURI = new URI(configuration.get(ParquetMetastoreSupport.FILTER_DIR))
  val fs = FileSystem.get(filterURI, configuration)

And it seems to be working fine. But just wanted to let you know and get your advice on whether that is the right fix.

**Comment by arunbhat** [comment]
Sure. I tried creating a PR - got permission denied. I created a new branch ISSUE-86 and tried to push it (to create the PR). Am I not doing this right?

**Comment by sadikovi** [comment]
You have to fork the repository and create PR from it: https://help.github.com/articles/creating-a-pull-request-from-a-fork/.

**Comment by arunbhat** [comment]
Duh :). Thanks. https://github.com/lightcopy/parquet-index/pull/87 - i am new to scala. So please check. Also I used maven to compile and test. Somehow sbt just wouldn't behave for me.
