### ISSUE TITLE
if sting type not support to create index or length 14 is too long

### ISSUE THREAD

**Issue by wonderfulping** [lightcopy/parquet-index#93]
![image](https://user-images.githubusercontent.com/7769527/61047290-b768aa80-a411-11e9-8fb2-cae4cb9a5121.png)
scala>     spark.index.create.indexBy("h_user_key").table("ensights.l_user_tag_par")
java.lang.UnsupportedOperationException: Schema contains unsupported type, field=StructField(h_user_key,BinaryType,true), schema=struct<h_user_key:binary>, supported types=[StringType, LongType, IntegerType, TimestampType, DateType]
  at org.apache.spark.sql.execution.datasources.parquet.ParquetSchemaUtils$$anonfun$validateStructType$1.apply(ParquetSchemaUtils.scala:47)
  at org.apache.spark.sql.execution.datasources.parquet.ParquetSchemaUtils$$anonfun$validateStructType$1.apply(ParquetSchemaUtils.scala:45)
  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
  at org.apache.spark.sql.execution.datasources.parquet.ParquetSchemaUtils$.validateStructType(ParquetSchemaUtils.scala:45)
  at org.apache.spark.sql.execution.datasources.parquet.ParquetStatisticsRDD.<init>(ParquetStatisticsRDD.scala:86)
  at org.apache.spark.sql.execution.datasources.parquet.ParquetMetastoreSupport.createIndex(ParquetMetastoreSupport.scala:139)
  at org.apache.spark.sql.execution.datasources.IndexedDataSource$$anonfun$createIndex$2.apply(IndexedDataSource.scala:108)
  at org.apache.spark.sql.execution.datasources.IndexedDataSource$$anonfun$createIndex$2.apply(IndexedDataSource.scala:107)
  at org.apache.spark.sql.execution.datasources.Metastore.create(Metastore.scala:162)
  at org.apache.spark.sql.execution.datasources.IndexedDataSource.createIndex(IndexedDataSource.scala:107)
  at org.apache.spark.sql.CreateIndexCommand.table(DataFrameIndexManager.scala:234)
  ... 50 elided

**Comment by sadikovi** [comment]
Oh, yes. Complex types are not supported, only top level atomic types.

**Comment by wonderfulping** [comment]
does that meaing string is support,h_user_key is string type but with md5 function and the lengh is 32 and can't work here

**Comment by sadikovi** [comment]
Oh, I see. We should support BinaryType. Currently, we don't support, but it should be easy to add. You can try to open a pull request if you want.
- You would have to add a binary type here: https://github.com/lightcopy/parquet-index/blob/master/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetSchemaUtils.scala#L33
- And then register statistics here: https://github.com/lightcopy/parquet-index/blob/7ef254eeb3c747898d491b0ac4596d98db68dac0/src/main/scala/org/apache/spark/sql/sources/ColumnStatistics.scala#L151

You can give it a go, I can help you debug it, if there are any issues.
