### ISSUE TITLE
how to read from HDFS multiple parquet files with spark.index.create .mode("overwrite").indexBy($"cellid").parquet

### ISSUE THREAD

**Issue by silviuchiric** [lightcopy/parquet-index#95]
![parquet_issue](https://user-images.githubusercontent.com/38807419/69949856-8d17a680-14f2-11ea-97eb-d9f070fdba30.JPG)
I have built from the master code, 
then successfully import the jar file in Jupyter Notebook(%AddJar file:/srv/home/srv-taurus-stage/sbd2-notebook/jupyter/parquet-index_2.11-0.4.1-SNAPSHOT.jar)
then I added the library too  *import com.github.lightcopy.implicits._)

However , when I try to create the index by providing the path to the parquet files  on HDFS          
spark.index.create
                 .mode("overwrite").indexBy($"cellid")
                 .parquet("hdfs://///data/taurus/stage/taurus.stage.counter-lte-eri-cell-raw-parquet/time=ingestion/bucket=hourly/date=2019-11-2*/*") that I checked one cell above for existence it fails:
Message: File does not exist: How the parquet method knows to read from hdfs, it looks like it does not like the context path hdfs:////

**Comment by sadikovi** [comment]
Can you attach the exception stacktrace?

**Comment by sadikovi** [comment]
Also, you have to use "hdfs://host:port/path" or "hdfs:/path", I don't know how it works with your path.

Does not work with regex very well. Suppose you have this directory:
```
data/
  taurus/
    stage/
      taurus.stage.counter-lte-eri-cell-raw-parquet/
        time=ingestion/
          bucket=hourly/
            date=2019-11-20/
            date=2019-11-21/
            date=2019-11-22/
```
Your path would be "data/taurus/stage/taurus.stage.counter-lte-eri-cell-raw-parquet" assuming that table has partitioning. You would have to read it as "data/taurus/stage/taurus.stage.counter-lte-eri-cell-raw-parquet" - Spark will automatically resolve partitioning and index will automatically load the column stats.

Otherwise, you can provide something like this: "data/taurus/stage/taurus.stage.counter-lte-eri-cell-raw-parquet/time=ingestion/bucket=hourly".

**Comment by silviuchiric** [comment]
Thank you Ivan
I did exaclty your advice:
So, please find attached

 the step by step cells :
1

import sys.process._

1

%AddJar file:/srv/home/srv-taurus-stage/sbd2-notebook/jupyter/parquet-index_2.11-0.4.1-SNAPSHOT.jar

Using cached version of parquet-index_2.11-0.4.1-SNAPSHOT.jar

1

import com.github.lightcopy.implicits._

import org.apache.spark.sql.functions._
import org.apache.spark.sql.types._
import org.apache.spark.sql.{Row, SaveMode, SparkSession, Column, DataFrame}
import org.apache.spark.sql.functions._
import java.io.File
import sys.process._
import org.apache.spark.sql.functions.max
import org.apache.spark.sql.functions.count
import org.apache.spark.sql.functions.format_number

val spark = SparkSession.builder()
            .appName("Spark Hive Example")
            .enableHiveSupport()
            .config("spark.dynamicAllocation.cachedExecutorIdleTimeout", "1200")
            .config("spark.driver.memory", "8g")
            .config("spark.dynamicAllocation.initialExecutors", "10")
            .config("spark.dynamicAllocation.minExecutors", "10")
            .config("spark.dynamicAllocation.maxExecutors", "50")
            .config("spark.executor.cores", "8")
            .config("spark.executor.instances", "40")
            .config("spark.executor.memory", "25g")
            .config("spark.yarn.queue", "default")
            .config("spark.sql.parquet.binaryAsString", "TRUE")
            .config("spark.sql.broadcastTimeout",  "360000")
            .config("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
            .config("spark.kryoserializer.buffer", "1024k")
            .config("spark.kryoserializer.buffer.max", "1024m")
            .config("spark.yarn.queue", "default")
            .config("spark.sql.shuffle.partitions", "300")
            .config("spark.jars", "parquet-index-0.4.0-s_2.11.jar")
            //.config("spark.sql.warehouse.dir", "hdfs://sp-h335-ms03.corproot.net:50470/user/hive/warehouse")
            //.config("hive.metastore.warehouse.dir", "hdfs://sp-h335-ms03.corproot.net:50470/user/hive/warehouse")
            .config("spark.sql.index.metastore", "hdfs://///data/taurus/stage/taurus.stage.counter-lte-eri-cell-raw-parquet/time=ingestion/bucket=hourly/")
            .getOrCreate()
import spark.implicits._
import spark.sql

"hdfs dfs -ls /data/taurus/stage/taurus.stage.counter-lte-eri-cell-raw-parquet" !
Found 1 items
drwx------   - srv-taurus-stage srv-taurus-stage          0 2019-10-01 17:00 /data/taurus/stage/taurus.stage.counter-lte-eri-cell-raw-parquet/time=ingestion

lastException: Throwable = null
warning: there was one feature warning; re-run with -feature for details

val df = spark.read
                .option("header", "true")
                .option("inferSchema", "true")
                .parquet("hdfs:/data/taurus/stage/taurus.stage.counter-lte-eri-cell-raw-parquet")
df = [NifiTopic: string, EPCID: string ... 1118 more fields]

lastException: Throwable = null

[NifiTopic: string, EPCID: string ... 1118 more fields]

spark.index.create
                 .mode("overwrite").indexBy($"cellid")
                 .parquet("hdfs:/data/taurus/stage/taurus.stage.counter-lte-eri-cell-raw-parquet")
lastException = null

Name: java.lang.NoClassDefFoundError
Message: org/apache/spark/sql/execution/datasources/parquet/ParquetToSparkSchemaConverter
StackTrace:   at org.apache.spark.sql.execution.datasources.parquet.ParquetMetastoreSupport.inferIndexSchema(ParquetMetastoreSupport.scala:196)
  at org.apache.spark.sql.execution.datasources.parquet.ParquetMetastoreSupport.createIndex(ParquetMetastoreSupport.scala:121)
  at org.apache.spark.sql.execution.datasources.IndexedDataSource$$anonfun$createIndex$2.apply(IndexedDataSource.scala:108)
  at org.apache.spark.sql.execution.datasources.IndexedDataSource$$anonfun$createIndex$2.apply(IndexedDataSource.scala:107)
  at org.apache.spark.sql.execution.datasources.Metastore.create(Metastore.scala:162)
  at org.apache.spark.sql.execution.datasources.IndexedDataSource.createIndex(IndexedDataSource.scala:107)
  at org.apache.spark.sql.CreateIndexCommand.createIndex(DataFrameIndexManager.scala:225)
  at org.apache.spark.sql.CreateIndexCommand.parquet(DataFrameIndexManager.scala:240)

I have tried also without .mode("overwrite"):

lastException = null

Name: java.io.IOException
Message: Path hdfs://sbd/data/taurus/stage/taurus.stage.counter-lte-eri-cell-raw-parquet/time=ingestion/bucket=hourly/source/parquet/hdfs/data/taurus/stage/taurus.stage.counter-lte-eri-cell-raw-parquet already exists, mode=ErrorIfExists
StackTrace:   at org.apache.spark.sql.execution.datasources.Metastore.create(Metastore.scala:148)
  at org.apache.spark.sql.execution.datasources.IndexedDataSource.createIndex(IndexedDataSource.scala:107)
  at org.apache.spark.sql.CreateIndexCommand.createIndex(DataFrameIndexManager.scala:225)
  at org.apache.spark.sql.CreateIndexCommand.parquet(DataFrameIndexManager.scala:240)

And then:
spark.index.exists.parquet("hdfs://sbd/tmp/19112019.parquet")

Out[22]: lastException: Throwable = null

             false

**Comment by sadikovi** [comment]
These errors are user errors, you can try cleaning up the working directory and running it again. See README for usage.

**Comment by sadikovi** [comment]
I would recommend you try creating index for a small and simple table and see if it works for you.

**Comment by sadikovi** [comment]
You can try examples from README, just replace path with HDFS path and see if it works for you.

**Comment by silviuchiric** [comment]
Hello Ivan
I have tried the example from ReadMe and get the same issue:

import org.apache.spark.sql.functions.{col, lit, when}

spark.range(0, 1000000).

  select($"id", $"id".cast("string").as("code"), lit("xyz").as("name")).

  repartition(400).

  write.partitionBy("name").parquet("/tmp/codes.parquet")

[Stage 1:======================================================>(394 + 2) / 400]

lastException: Throwable = null

1

spark.index.create.

2

  mode("overwrite").indexBy($"id", $"code").parquet("/tmp/codes.parquet")

lastException = null

Name: java.lang.NoClassDefFoundError
Message: org/apache/spark/sql/execution/datasources/parquet/ParquetToSparkSchemaConverter
StackTrace:   at org.apache.spark.sql.execution.datasources.parquet.ParquetMetastoreSupport.inferIndexSchema(ParquetMetastoreSupport.scala:196)
  at org.apache.spark.sql.execution.datasources.parquet.ParquetMetastoreSupport.createIndex(ParquetMetastoreSupport.scala:121)
  at org.apache.spark.sql.execution.datasources.IndexedDataSource$$anonfun$createIndex$2.apply(IndexedDataSource.scala:108)
  at org.apache.spark.sql.execution.datasources.IndexedDataSource$$anonfun$createIndex$2.apply(IndexedDataSource.scala:107)
  at org.apache.spark.sql.execution.datasources.Metastore.create(Metastore.scala:162)
  at org.apache.spark.sql.execution.datasources.IndexedDataSource.createIndex(IndexedDataSource.scala:107)
  at org.apache.spark.sql.CreateIndexCommand.createIndex(DataFrameIndexManager.scala:225)
  at org.apache.spark.sql.CreateIndexCommand.parquet(DataFrameIndexManager.scala:240)
  ... 58 elided
Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.execution.datasources.parquet.ParquetToSparkSchemaConverter
  at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by silviuchiric** [comment]
Will you please send me your parquet-index_2.11-0.4.1-SNAPSHOT.jar for Scala that works please?

**Comment by sadikovi** [comment]
What Spark version are you using? Is it a custom build?

**Comment by silviuchiric** [comment]
Hi Ivan 
spark = org.apache.spark.sql.SparkSession@12624209
Nothing custom, but version
2.2.0.2.6.4.0-91
I am using it with Apache Toree - Scala
And this tis the SparkSession:
import org.apache.spark.sql.functions._
import org.apache.spark.sql.types._
import org.apache.spark.sql.{Row, SaveMode, SparkSession, Column, DataFrame}
import org.apache.spark.sql.functions._
import java.io.File
import sys.process._
import org.apache.spark.sql.functions.max
import org.apache.spark.sql.functions.count
import org.apache.spark.sql.functions.format_number

val spark = SparkSession.builder()
            .appName("Spark Hive Example")
            .enableHiveSupport()
            .config("spark.dynamicAllocation.cachedExecutorIdleTimeout", "1200")
            .config("spark.driver.memory", "8g")
            .config("spark.dynamicAllocation.initialExecutors", "10")
            .config("spark.dynamicAllocation.minExecutors", "10")
            .config("spark.dynamicAllocation.maxExecutors", "50")
            .config("spark.executor.cores", "8")
            .config("spark.executor.instances", "40")
            .config("spark.executor.memory", "25g")
            .config("spark.yarn.queue", "default")
            .config("spark.sql.parquet.binaryAsString", "TRUE")
            .config("spark.sql.broadcastTimeout",  "360000")
            .config("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
            .config("spark.kryoserializer.buffer", "1024k")
            .config("spark.kryoserializer.buffer.max", "1024m")
            .config("spark.yarn.queue", "default")
            .config("spark.sql.shuffle.partitions", "300")
            .config("spark.jars", "parquet-index-0.4.0-s_2.11.jar")
            .config("spark.sql.warehouse.dir", "/data/taurus/stage/taurus.stage.counter-lte-eri-cell-raw-parquet")
            .config("hive.metastore.warehouse.dir", "/data/taurus/stage/taurus.stage.counter-lte-eri-cell-raw-parquet")
            .config("spark.yarn.security.credentials.hive.enabled", "true")
            .getOrCreate()
import spark.implicits._
import spark.sql
sc.version

**Comment by sadikovi** [comment]
That is not an official Spark version: 2.2.0.2.6.4.0-91.

I just tested parquet-index 0.4.0 on Spark 2.2.0 and everything seems to be working fine.

**Comment by silviuchiric** [comment]
Hi Ivan
I am in an enterprise env, is it however possible to choose which version to use somehow? 
We also have latest version 
spark-2.4.4
Anyway, will you please add the parquet-index 0.4.0. jar file, may be my build is incomplete somehow(very unlikely, because I did not get any error and got the .jar generated, but just to double check)--
Thanks for your support!
SIlviu Chiric

**Comment by sadikovi** [comment]
Latest master branch builds for Spark 2.4.4 and passes all tests.
0.4.0 builds for Spark 2.2 and passes all tests.

I attached the parquet-index jar that is built for Spark 2.4.4. You can try that.
[parquet-index_2.11-0.4.1-SNAPSHOT.jar.zip](https://github.com/lightcopy/parquet-index/files/3933915/parquet-index_2.11-0.4.1-SNAPSHOT.jar.zip)

Otherwise, you can just run: `sbt package` should create a jar that you can use.

It seems like you are running it on YARN, which I have not tested so I can't help you much without a small code snippet that I can use to reproduce and debug.

I don't know what enterprise version you are using. This is open-source project so naturally there is no enterprise support. You would need to ask your vendor to help you with that.
